package automat;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MontoerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MontoerPanel
     */
    
    static LogEvent log = new LogEvent();
    
    //File file = new File("")
    
    
    
    public MontoerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guiMontoer = new javax.swing.JButton();
        guiAfslut = new javax.swing.JButton();
        guiZoneSæt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        guiZoneVælger = new javax.swing.JComboBox<>();
        guiZoneSted = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        guiIndlæs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        guiLog = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(640, 480));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("MONTØRINSTILLINGER");

        guiMontoer.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        guiMontoer.setText("Log ud");
        guiMontoer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiMontoerActionPerformed(evt);
            }
        });

        guiAfslut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        guiAfslut.setText("Afslut");
        guiAfslut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiAfslutActionPerformed(evt);
            }
        });

        guiZoneSæt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        guiZoneSæt.setText("Sæt");
        guiZoneSæt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiZoneSætActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Indlæs Montør log");

        guiZoneVælger.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        guiZoneVælger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        guiZoneSted.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        guiZoneSted.setText("Billetautomat er i zone: " + MenuPanel.automat.getAutomatZone());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Sæt ny zone for automat:");

        guiIndlæs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        guiIndlæs.setText("Indlæs");
        guiIndlæs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiIndlæsActionPerformed(evt);
            }
        });

        guiLog.setColumns(20);
        guiLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        guiLog.setRows(5);
        jScrollPane1.setViewportView(guiLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guiZoneVælger, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiZoneSæt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guiIndlæs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(guiZoneSted))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                        .addComponent(guiAfslut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiMontoer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addContainerGap(598, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(guiMontoer)
                    .addComponent(guiAfslut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guiZoneSted, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guiZoneVælger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiZoneSæt))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiIndlæs)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guiMontoerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiMontoerActionPerformed
        MenuPanel.automat.setMontoertilstand(false);                            // Sætter montoertilsantd FALSE
        try {
            MontoerPanel.log.LogEvent(2, 0, "Admin", 0);
        } catch (IOException ex) {
            Logger.getLogger(MontoerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        StartFrame.fane.setSelectedIndex(0);                                    // Omddirigerer tilbage til startfanen
    }//GEN-LAST:event_guiMontoerActionPerformed

    private void guiAfslutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiAfslutActionPerformed
        MenuPanel.clear();                                                      // 
        StartFrame.fane.setSelectedIndex(0);                                    // Omdirigerer tilbage til startfane
    }//GEN-LAST:event_guiAfslutActionPerformed

    private void guiZoneSætActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiZoneSætActionPerformed
        ZonePanel.beregner.setAutomatZone(guiZoneVælger.getSelectedIndex()+1);  // Kalder funktionen setAutomatZone, ændrer denne værdi til ønsket lokation
        ZonePanel.guiEgenZone.setText("Du er i zone: " + ZonePanel.beregner.getAutomatZone());
        guiZoneSted.setText("Billetautomat er i zone: " + ZonePanel.beregner.getAutomatZone() + " ");
    }//GEN-LAST:event_guiZoneSætActionPerformed

    private void guiIndlæsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiIndlæsActionPerformed
        try {
            log.printLog();
        } catch (IOException ex) {
            Logger.getLogger(MontoerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guiIndlæsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiAfslut;
    private javax.swing.JButton guiIndlæs;
    public static javax.swing.JTextArea guiLog;
    private javax.swing.JButton guiMontoer;
    public static javax.swing.JLabel guiZoneSted;
    private javax.swing.JButton guiZoneSæt;
    private javax.swing.JComboBox<String> guiZoneVælger;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
} // End of class Montoer panel
