/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automat;

/**
 *
 * @author Robert
 */
public class StartPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    
    int zoner = 1;
    int antal = 1;
    
    public StartPanel() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        billettype = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        zoneMinus = new javax.swing.JButton();
        zonePlus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        antalMinus = new javax.swing.JButton();
        antalPlus = new javax.swing.JButton();
        antalAntal = new javax.swing.JLabel();
        antalZoner = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("BILLETAUTOMAT");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Vælg Billettype");

        billettype.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        billettype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Voksen", "Børn", "Studerende", "Pensionist", "Cykel", "Hund" }));
        billettype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billettypeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Zone");

        zoneMinus.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        zoneMinus.setText("-");
        zoneMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneMinusActionPerformed(evt);
            }
        });

        zonePlus.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        zonePlus.setText("+");
        zonePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonePlusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Antal");

        antalMinus.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        antalMinus.setText("-");
        antalMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antalMinusActionPerformed(evt);
            }
        });

        antalPlus.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        antalPlus.setText("+");
        antalPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antalPlusActionPerformed(evt);
            }
        });

        antalAntal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        antalAntal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        antalAntal.setText("1");
        antalAntal.setToolTipText("");

        antalZoner.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        antalZoner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        antalZoner.setText("1");
        antalZoner.setToolTipText("");

        jButton1.setText("1738");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billettype, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(zoneMinus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(antalZoner, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(antalMinus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(antalAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(antalPlus)
                                    .addComponent(zonePlus))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel4))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billettype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zonePlus)
                    .addComponent(zoneMinus)
                    .addComponent(antalZoner))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antalPlus)
                    .addComponent(antalMinus)
                    .addComponent(antalAntal)
                    .addComponent(jButton1))
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zoneMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneMinusActionPerformed
        // TODO add your handling code here:
        if (zoner > 1){
            zoner--;
        }
        antalZoner.setText(" "+ zoner + " ");
    }//GEN-LAST:event_zoneMinusActionPerformed

    private void zonePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonePlusActionPerformed
        // TODO add your handling code here:
        if (zoner < 6){
            zoner++;
        }
        antalZoner.setText(" "+ zoner + " ");
    }//GEN-LAST:event_zonePlusActionPerformed

    private void antalMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antalMinusActionPerformed
        // TODO add your handling code here:
        if (antal > 1){
            antal--;
        }        
        antalAntal.setText(" "+ antal + " ");
    }//GEN-LAST:event_antalMinusActionPerformed

    private void antalPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antalPlusActionPerformed
        // TODO add your handling code here:
       
        antal++;
               
        antalAntal.setText(" "+ antal + " ");
    }//GEN-LAST:event_antalPlusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        antal = 1738;
        antalAntal.setText(" " + antal + " ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void billettypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billettypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billettypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antalAntal;
    private javax.swing.JButton antalMinus;
    private javax.swing.JButton antalPlus;
    private javax.swing.JLabel antalZoner;
    private javax.swing.JComboBox<String> billettype;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton zoneMinus;
    private javax.swing.JButton zonePlus;
    // End of variables declaration//GEN-END:variables
}
